<?php   
include('../controller/db_functions.php');
$pdo = conectar();



function insertpessoa(
    $nome,
    $tipopessoa,
    $cpf,
    $rg,
    $orgaoem,
    $sexo,
    $profissao,
    $nacionalidade,
    $naturalidade,
    $datanascimento,
    $estadocivil,
    $endereco,
    $bairro,
    $cidade,
    $nomepai,
    $nomemae
)
{
$pdo = conectar();


$nome = addslashes($nome);
$endereco = addslashes($endereco);
$bairro = addslashes($bairro);
$naturalidade = addslashes($naturalidade);
$cidade = addslashes($cidade);
$nomepai = addslashes($nomepai);
$nomemae = addslashes($nomemae);
$profissao = addslashes($profissao);
$nacionalidade = addslashes($nacionalidade);

if (empty($estadocivil) || strlen($estadocivil)>3) {
$estadocivil = 'SO';
}

$query = "INSERT INTO `pessoa` (`ID`, `setTipoPessoa`, `hiddencaminhofoto`, `strNome`, `strRazaoSocial`, `strCPFcnpj`, `strRG`, `strOrgaoEm`, `strProfissao`, `strNaturalidade`, `setSexo`, `strNacionalidade`, `dataNascimento`, `setEstadoCivil`, `strNomeFilhos`, `strNomeConjuge`, `strNomeExConjuge`, `dataCasamento`, `strCartorioCasamento`, `strLogradouro`, `strEmail`, `strBairro`, `intUFcidade`, `strUF`, `strTelefone`, `strTelCelular`, `strNomePai`, `strNomeMae`, `dataCadastro`, `strRepresentante1`, `strRepresentante2`, `strRepresentante3`, `strObservacao`, `setRegimeBens`, `dataEmissao`, `strFicha`, `scanImgAssinatura`, `scanImgDigital`, `RETORNOSELODIGITAL`, `pessoa_viva`, `tipo_cadastro`, `descdocestrangeiro`, `docestrangeiro`, `cpfRepresentante1`, `cpfRepresentante2`, `cpfRepresentante3`) VALUES (NULL, 'F', NULL, '$nome', NULL, '$cpf', '$rg', '$orgaoem', '$profissao', '$naturalidade', '$sexo', '$nacionalidade', '$datanascimento', '$estadocivil', NULL, NULL, NULL, NULL, NULL, '$endereco', NULL, '$bairro', '$cidade', 'MA', NULL, NULL, '$nomepai', '$nomemae', CURRENT_TIMESTAMP, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);";


//VENDO SE NÃO JA ESTÁ NA TABELA
$busca = $pdo->prepare("SELECT strCPFcnpj FROM pessoa where strCPFcnpj = '$cpf' limit 1");
if (strlen($cpf) < 9) {
$busca = $pdo->prepare("SELECT ID FROM pessoa where strNome = '$nome' and dataNascimento = '$datanascimento' and strNaturalidade = '$naturalidade' and strProfissao = '$profissao' limit 1");   
}
$busca->execute();
if($busca->rowCount()<1 || empty($cpf))
{
	if(!empty($nome) && strlen($nome) > 5){
    $inpessoas = $pdo->prepare($query);
    if($inpessoas->execute()){
        $id = $pdo->prepare("SELECT ID from pessoa ORDER BY ID DESC LIMIT 1");
        $id->execute();
        $bid = $id->fetch(PDO::FETCH_ASSOC);
        $lastid = $bid['ID'];
        return $lastid;
    }

    else{
        return "REGISTRO NÃO INSERIDO <br>";
    }
}
}
else{
	return "ja encontrado na tabela pessoas<br>";
}

}



//FORMATANDO DADOS CASAMENTO ------- 

$busca = $pdo->prepare("SELECT * FROM registro_casamento_novo where DATAENTRADA < '2021-01-01'");
$busca->execute();
$linha = $busca->fetchAll(PDO::FETCH_OBJ);
foreach ($linha as $b){



echo "REGISTRO CASAMENTO:".$b->ID."--------------------------------- <br>";

/*
echo "OBTENDOS DADOS DO NUBENTE1: <br>";


$NOMENUBENTE1 = $b->NOMENUBENTE1;
$CPFNUBENTE1 = $b->CPFNUBENTE1;
$NACIONALIDADENUBENTE1 = $b->NACIONALIDADENUBENTE1;
$NATURALIDADENUBENTE1 = $b->NATURALIDADENUBENTE1;
$RGNUBENTE1 = $b->RGNUBENTE1;
$ORGAOEMISSORNUBENTE1 = $b->ORGAOEMISSORNUBENTE1;
$CIDADENUBENTE1 = $b->CIDADENUBENTE1;
$ENDERECONUBENTE1 = $b->ENDERECONUBENTE1;
$BAIRRONUBENTE1 = $b->BAIRRONUBENTE1;
$ESTADOCIVILNUBENTE1 = $b->ESTADOCIVILNUBENTE1;
$DATANASCIMENTONUBENTE1 = $b->DATANASCIMENTONUBENTE1;
$SEXONUBENTE1 = $b->SEXONUBENTE1;
$PROFISSAONUBENTE1 = $b->PROFISSAONUBENTE1;
$NOMEPAINUBENTE1 = $b->NOMEPAINUBENTE1;
$NOMEMAENUBENTE1 = $b->NOMEMAENUBENTE1;


$IDNUBENTE1 = insertpessoa($NOMENUBENTE1,'F',$CPFNUBENTE1,$RGNUBENTE1,$ORGAOEMISSORNUBENTE1,$SEXONUBENTE1,$PROFISSAONUBENTE1,$NACIONALIDADENUBENTE1,$NATURALIDADENUBENTE1,$DATANASCIMENTONUBENTE1,$ESTADOCIVILNUBENTE1,$ENDERECONUBENTE1,$BAIRRONUBENTE1,$CIDADENUBENTE1,$NOMEPAINUBENTE1,$NOMEMAENUBENTE1);

echo $IDNUBENTE1."<br>";



echo "OBTENDOS DADOS DO PAINUBENTE1: <br>";


$NOMEPAINUBENTE1 = $b->NOMEPAINUBENTE1;
$CPFPAINUBENTE1 = $b->CPFPAINUBENTE1;
$NACIONALIDADEPAINUBENTE1 = $b->NACIONALIDADEPAINUBENTE1;
$NATURALIDADEPAINUBENTE1 = $b->NATURALIDADEPAINUBENTE1;
$RGPAINUBENTE1 = $b->RGPAINUBENTE1;
$ORGAOEMISSORPAINUBENTE1 = $b->ORGAOEMISSORPAINUBENTE1;
$CIDADEPAINUBENTE1 = $b->CIDADEPAINUBENTE1;
$ENDERECOPAINUBENTE1 = $b->ENDERECOPAINUBENTE1;
$BAIRROPAINUBENTE1 = $b->BAIRROPAINUBENTE1;
$ESTADOCIVILPAINUBENTE1 = $b->ESTADOCIVILPAINUBENTE1;
$DATANASCIMENTOPAINUBENTE1 = $b->DATANASCIMENTOPAINUBENTE1;
$SEXOPAINUBENTE1 = $b->SEXOPAINUBENTE1;
$PROFISSAOPAINUBENTE1 = $b->PROFISSAOPAINUBENTE1;



$IDPAINUBENTE1 = insertpessoa($NOMEPAINUBENTE1,'F',$CPFPAINUBENTE1,$RGPAINUBENTE1,$ORGAOEMISSORPAINUBENTE1,$SEXOPAINUBENTE1,$PROFISSAOPAINUBENTE1,$NACIONALIDADEPAINUBENTE1,$NATURALIDADEPAINUBENTE1,$DATANASCIMENTOPAINUBENTE1,$ESTADOCIVILPAINUBENTE1,$ENDERECOPAINUBENTE1,$BAIRROPAINUBENTE1,$CIDADEPAINUBENTE1,"","");

echo $IDPAINUBENTE1."<br>";




echo "OBTENDOS DADOS DO MAENUBENTE1: <br>";


$NOMEMAENUBENTE1 = $b->NOMEMAENUBENTE1;
$CPFMAENUBENTE1 = $b->CPFMAENUBENTE1;
$NACIONALIDADEMAENUBENTE1 = $b->NACIONALIDADEMAENUBENTE1;
$NATURALIDADEMAENUBENTE1 = $b->NATURALIDADEMAENUBENTE1;
$RGMAENUBENTE1 = $b->RGMAENUBENTE1;
$ORGAOEMISSORMAENUBENTE1 = $b->ORGAOEMISSORMAENUBENTE1;
$CIDADEMAENUBENTE1 = $b->CIDADEMAENUBENTE1;
$ENDERECOMAENUBENTE1 = $b->ENDERECOMAENUBENTE1;
$BAIRROMAENUBENTE1 = $b->BAIRROMAENUBENTE1;
$ESTADOCIVILMAENUBENTE1 = $b->ESTADOCIVILMAENUBENTE1;
$DATANASCIMENTOMAENUBENTE1 = $b->DATANASCIMENTOMAENUBENTE1;
$SEXOMAENUBENTE1 = $b->SEXOMAENUBENTE1;
$PROFISSAOMAENUBENTE1 = $b->PROFISSAOMAENUBENTE1;



$IDMAENUBENTE1 = insertpessoa($NOMEMAENUBENTE1,'F',$CPFMAENUBENTE1,$RGMAENUBENTE1,$ORGAOEMISSORMAENUBENTE1,$SEXOMAENUBENTE1,$PROFISSAOMAENUBENTE1,$NACIONALIDADEMAENUBENTE1,$NATURALIDADEMAENUBENTE1,$DATANASCIMENTOMAENUBENTE1,$ESTADOCIVILMAENUBENTE1,$ENDERECOMAENUBENTE1,$BAIRROMAENUBENTE1,$CIDADEMAENUBENTE1,"","");

echo $IDMAENUBENTE1."<br>";




echo "OBTENDOS DADOS DO NUBENTE2: <br>";


$NOMENUBENTE2 = $b->NOMENUBENTE2;
$CPFNUBENTE2 = $b->CPFNUBENTE2;
$NACIONALIDADENUBENTE2 = $b->NACIONALIDADENUBENTE2;
$NATURALIDADENUBENTE2 = $b->NATURALIDADENUBENTE2;
$RGNUBENTE2 = $b->RGNUBENTE2;
$ORGAOEMISSORNUBENTE2 = $b->ORGAOEMISSORNUBENTE2;
$CIDADENUBENTE2 = $b->CIDADENUBENTE2;
$ENDERECONUBENTE2 = $b->ENDERECONUBENTE2;
$BAIRRONUBENTE2 = $b->BAIRRONUBENTE2;
$ESTADOCIVILNUBENTE2 = $b->ESTADOCIVILNUBENTE2;
$DATANASCIMENTONUBENTE2 = $b->DATANASCIMENTONUBENTE2;
$SEXONUBENTE2 = $b->SEXONUBENTE2;
$PROFISSAONUBENTE2 = $b->PROFISSAONUBENTE2;
$NOMEPAINUBENTE2 = $b->NOMEPAINUBENTE2;
$NOMEMAENUBENTE2 = $b->NOMEMAENUBENTE2;


$IDNUBENTE2 = insertpessoa($NOMENUBENTE2,'F',$CPFNUBENTE2,$RGNUBENTE2,$ORGAOEMISSORNUBENTE2,$SEXONUBENTE2,$PROFISSAONUBENTE2,$NACIONALIDADENUBENTE2,$NATURALIDADENUBENTE2,$DATANASCIMENTONUBENTE2,$ESTADOCIVILNUBENTE2,$ENDERECONUBENTE2,$BAIRRONUBENTE2,$CIDADENUBENTE2,$NOMEPAINUBENTE2,$NOMEMAENUBENTE2);

echo $IDNUBENTE2."<br>";



echo "OBTENDOS DADOS DO PAINUBENTE2: <br>";


$NOMEPAINUBENTE2 = $b->NOMEPAINUBENTE2;
$CPFPAINUBENTE2 = $b->CPFPAINUBENTE2;
$NACIONALIDADEPAINUBENTE2 = $b->NACIONALIDADEPAINUBENTE2;
$NATURALIDADEPAINUBENTE2 = $b->NATURALIDADEPAINUBENTE2;
$RGPAINUBENTE2 = $b->RGPAINUBENTE2;
$ORGAOEMISSORPAINUBENTE2 = $b->ORGAOEMISSORPAINUBENTE2;
$CIDADEPAINUBENTE2 = $b->CIDADEPAINUBENTE2;
$ENDERECOPAINUBENTE2 = $b->ENDERECOPAINUBENTE2;
$BAIRROPAINUBENTE2 = $b->BAIRROPAINUBENTE2;
$ESTADOCIVILPAINUBENTE2 = $b->ESTADOCIVILPAINUBENTE2;
$DATANASCIMENTOPAINUBENTE2 = $b->DATANASCIMENTOPAINUBENTE2;
$SEXOPAINUBENTE2 = $b->SEXOPAINUBENTE2;
$PROFISSAOPAINUBENTE2 = $b->PROFISSAOPAINUBENTE2;



$IDPAINUBENTE2 = insertpessoa($NOMEPAINUBENTE2,'F',$CPFPAINUBENTE2,$RGPAINUBENTE2,$ORGAOEMISSORPAINUBENTE2,$SEXOPAINUBENTE2,$PROFISSAOPAINUBENTE2,$NACIONALIDADEPAINUBENTE2,$NATURALIDADEPAINUBENTE2,$DATANASCIMENTOPAINUBENTE2,$ESTADOCIVILPAINUBENTE2,$ENDERECOPAINUBENTE2,$BAIRROPAINUBENTE2,$CIDADEPAINUBENTE2,"","");

echo $IDPAINUBENTE2."<br>";




echo "OBTENDOS DADOS DO MAENUBENTE2: <br>";


$NOMEMAENUBENTE2 = $b->NOMEMAENUBENTE2;
$CPFMAENUBENTE2 = $b->CPFMAENUBENTE2;
$NACIONALIDADEMAENUBENTE2 = $b->NACIONALIDADEMAENUBENTE2;
$NATURALIDADEMAENUBENTE2 = $b->NATURALIDADEMAENUBENTE2;
$RGMAENUBENTE2 = $b->RGMAENUBENTE2;
$ORGAOEMISSORMAENUBENTE2 = $b->ORGAOEMISSORMAENUBENTE2;
$CIDADEMAENUBENTE2 = $b->CIDADEMAENUBENTE2;
$ENDERECOMAENUBENTE2 = $b->ENDERECOMAENUBENTE2;
$BAIRROMAENUBENTE2 = $b->BAIRROMAENUBENTE2;
$ESTADOCIVILMAENUBENTE2 = $b->ESTADOCIVILMAENUBENTE2;
$DATANASCIMENTOMAENUBENTE2 = $b->DATANASCIMENTOMAENUBENTE2;
$SEXOMAENUBENTE2 = $b->SEXOMAENUBENTE2;
$PROFISSAOMAENUBENTE2 = $b->PROFISSAOMAENUBENTE2;



$IDMAENUBENTE2 = insertpessoa($NOMEMAENUBENTE2,'F',$CPFMAENUBENTE2,$RGMAENUBENTE2,$ORGAOEMISSORMAENUBENTE2,$SEXOMAENUBENTE2,$PROFISSAOMAENUBENTE2,$NACIONALIDADEMAENUBENTE2,$NATURALIDADEMAENUBENTE2,$DATANASCIMENTOMAENUBENTE2,$ESTADOCIVILMAENUBENTE2,$ENDERECOMAENUBENTE2,$BAIRROMAENUBENTE2,$CIDADEMAENUBENTE2,"","");

echo $IDMAENUBENTE2."<br>";



echo "OBTENDOS DADOS DO TESTEMUNHA1: <br>";


$NOMETESTEMUNHA1 = $b->NOMETESTEMUNHA1;
$CPFTESTEMUNHA1 = $b->CPFTESTEMUNHA1;
$NACIONALIDADETESTEMUNHA1 = $b->NACIONALIDADETESTEMUNHA1;
$NATURALIDADETESTEMUNHA1 = $b->NATURALIDADETESTEMUNHA1;
$RGTESTEMUNHA1 = $b->RGTESTEMUNHA1;
$ORGAOEMISSORTESTEMUNHA1 = $b->ORGAOEMISSORTESTEMUNHA1;
$CIDADETESTEMUNHA1 = $b->CIDADETESTEMUNHA1;
$ENDERECOTESTEMUNHA1 = $b->ENDERECOTESTEMUNHA1;
$BAIRROTESTEMUNHA1 = $b->BAIRROTESTEMUNHA1;
$ESTADOCIVILTESTEMUNHA1 = $b->ESTADOCIVILTESTEMUNHA1;
$DATANASCIMENTOTESTEMUNHA1 = $b->DATANASCIMENTOTESTEMUNHA1;
$SEXOTESTEMUNHA1 = $b->SEXOTESTEMUNHA1;
$PROFISSAOTESTEMUNHA1 = $b->PROFISSAOTESTEMUNHA1;



$IDTESTEMUNHA1 = insertpessoa($NOMETESTEMUNHA1,'F',$CPFTESTEMUNHA1,$RGTESTEMUNHA1,$ORGAOEMISSORTESTEMUNHA1,$SEXOTESTEMUNHA1,$PROFISSAOTESTEMUNHA1,$NACIONALIDADETESTEMUNHA1,$NATURALIDADETESTEMUNHA1,$DATANASCIMENTOTESTEMUNHA1,$ESTADOCIVILTESTEMUNHA1,$ENDERECOTESTEMUNHA1,$BAIRROTESTEMUNHA1,$CIDADETESTEMUNHA1,"","");

echo $IDTESTEMUNHA1."<br>";




echo "OBTENDOS DADOS DO TESTEMUNHA2: <br>";


$NOMETESTEMUNHA2 = $b->NOMETESTEMUNHA2;
$CPFTESTEMUNHA2 = $b->CPFTESTEMUNHA2;
$NACIONALIDADETESTEMUNHA2 = $b->NACIONALIDADETESTEMUNHA2;
$NATURALIDADETESTEMUNHA2 = $b->NATURALIDADETESTEMUNHA2;
$RGTESTEMUNHA2 = $b->RGTESTEMUNHA2;
$ORGAOEMISSORTESTEMUNHA2 = $b->ORGAOEMISSORTESTEMUNHA2;
$CIDADETESTEMUNHA2 = $b->CIDADETESTEMUNHA2;
$ENDERECOTESTEMUNHA2 = $b->ENDERECOTESTEMUNHA2;
$BAIRROTESTEMUNHA2 = $b->BAIRROTESTEMUNHA2;
$ESTADOCIVILTESTEMUNHA2 = $b->ESTADOCIVILTESTEMUNHA2;
$DATANASCIMENTOTESTEMUNHA2 = $b->DATANASCIMENTOTESTEMUNHA2;
$SEXOTESTEMUNHA2 = $b->SEXOTESTEMUNHA2;
$PROFISSAOTESTEMUNHA2 = $b->PROFISSAOTESTEMUNHA2;



$IDTESTEMUNHA2 = insertpessoa($NOMETESTEMUNHA2,'F',$CPFTESTEMUNHA2,$RGTESTEMUNHA2,$ORGAOEMISSORTESTEMUNHA2,$SEXOTESTEMUNHA2,$PROFISSAOTESTEMUNHA2,$NACIONALIDADETESTEMUNHA2,$NATURALIDADETESTEMUNHA2,$DATANASCIMENTOTESTEMUNHA2,$ESTADOCIVILTESTEMUNHA2,$ENDERECOTESTEMUNHA2,$BAIRROTESTEMUNHA2,$CIDADETESTEMUNHA2,"","");

echo $IDTESTEMUNHA2."<br>";


echo "OBTENDOS DADOS DO TESTEMUNHA3: <br>";


$NOMETESTEMUNHA3 = $b->NOMETESTEMUNHA3;
$CPFTESTEMUNHA3 = $b->CPFTESTEMUNHA3;
$NACIONALIDADETESTEMUNHA3 = $b->NACIONALIDADETESTEMUNHA3;
$NATURALIDADETESTEMUNHA3 = $b->NATURALIDADETESTEMUNHA3;
$RGTESTEMUNHA3 = $b->RGTESTEMUNHA3;
$ORGAOEMISSORTESTEMUNHA3 = $b->ORGAOEMISSORTESTEMUNHA3;
$CIDADETESTEMUNHA3 = $b->CIDADETESTEMUNHA3;
$ENDERECOTESTEMUNHA3 = $b->ENDERECOTESTEMUNHA3;
$BAIRROTESTEMUNHA3 = $b->BAIRROTESTEMUNHA3;
$ESTADOCIVILTESTEMUNHA3 = $b->ESTADOCIVILTESTEMUNHA3;
$DATANASCIMENTOTESTEMUNHA3 = $b->DATANASCIMENTOTESTEMUNHA3;
$SEXOTESTEMUNHA3 = $b->SEXOTESTEMUNHA3;
$PROFISSAOTESTEMUNHA3 = $b->PROFISSAOTESTEMUNHA3;



$IDTESTEMUNHA3 = insertpessoa($NOMETESTEMUNHA3,'F',$CPFTESTEMUNHA3,$RGTESTEMUNHA3,$ORGAOEMISSORTESTEMUNHA3,$SEXOTESTEMUNHA3,$PROFISSAOTESTEMUNHA3,$NACIONALIDADETESTEMUNHA3,$NATURALIDADETESTEMUNHA3,$DATANASCIMENTOTESTEMUNHA3,$ESTADOCIVILTESTEMUNHA3,$ENDERECOTESTEMUNHA3,$BAIRROTESTEMUNHA3,$CIDADETESTEMUNHA3,"","");

echo $IDTESTEMUNHA3."<br>";

echo "OBTENDOS DADOS DO TESTEMUNHA4: <br>";


$NOMETESTEMUNHA4 = $b->NOMETESTEMUNHA4;
$CPFTESTEMUNHA4 = $b->CPFTESTEMUNHA4;
$NACIONALIDADETESTEMUNHA4 = $b->NACIONALIDADETESTEMUNHA4;
$NATURALIDADETESTEMUNHA4 = $b->NATURALIDADETESTEMUNHA4;
$RGTESTEMUNHA4 = $b->RGTESTEMUNHA4;
$ORGAOEMISSORTESTEMUNHA4 = $b->ORGAOEMISSORTESTEMUNHA4;
$CIDADETESTEMUNHA4 = $b->CIDADETESTEMUNHA4;
$ENDERECOTESTEMUNHA4 = $b->ENDERECOTESTEMUNHA4;
$BAIRROTESTEMUNHA4 = $b->BAIRROTESTEMUNHA4;
$ESTADOCIVILTESTEMUNHA4 = $b->ESTADOCIVILTESTEMUNHA4;
$DATANASCIMENTOTESTEMUNHA4 = $b->DATANASCIMENTOTESTEMUNHA4;
$SEXOTESTEMUNHA4 = $b->SEXOTESTEMUNHA4;
$PROFISSAOTESTEMUNHA4 = $b->PROFISSAOTESTEMUNHA4;



$IDTESTEMUNHA4 = insertpessoa($NOMETESTEMUNHA4,'F',$CPFTESTEMUNHA4,$RGTESTEMUNHA4,$ORGAOEMISSORTESTEMUNHA4,$SEXOTESTEMUNHA4,$PROFISSAOTESTEMUNHA4,$NACIONALIDADETESTEMUNHA4,$NATURALIDADETESTEMUNHA4,$DATANASCIMENTOTESTEMUNHA4,$ESTADOCIVILTESTEMUNHA4,$ENDERECOTESTEMUNHA4,$BAIRROTESTEMUNHA4,$CIDADETESTEMUNHA4,"","");

echo $IDTESTEMUNHA4."<br>";


echo "OBTENDOS DADOS DO TESTEMUNHA5: <br>";


$NOMETESTEMUNHA5 = $b->NOMETESTEMUNHA5;
$CPFTESTEMUNHA5 = $b->CPFTESTEMUNHA5;
$NACIONALIDADETESTEMUNHA5 = $b->NACIONALIDADETESTEMUNHA5;
$NATURALIDADETESTEMUNHA5 = $b->NATURALIDADETESTEMUNHA5;
$RGTESTEMUNHA5 = $b->RGTESTEMUNHA5;
$ORGAOEMISSORTESTEMUNHA5 = $b->ORGAOEMISSORTESTEMUNHA5;
$CIDADETESTEMUNHA5 = $b->CIDADETESTEMUNHA5;
$ENDERECOTESTEMUNHA5 = $b->ENDERECOTESTEMUNHA5;
$BAIRROTESTEMUNHA5 = $b->BAIRROTESTEMUNHA5;
$ESTADOCIVILTESTEMUNHA5 = $b->ESTADOCIVILTESTEMUNHA5;
$DATANASCIMENTOTESTEMUNHA5 = $b->DATANASCIMENTOTESTEMUNHA5;
$SEXOTESTEMUNHA5 = $b->SEXOTESTEMUNHA5;
$PROFISSAOTESTEMUNHA5 = $b->PROFISSAOTESTEMUNHA5;



$IDTESTEMUNHA5 = insertpessoa($NOMETESTEMUNHA5,'F',$CPFTESTEMUNHA5,$RGTESTEMUNHA5,$ORGAOEMISSORTESTEMUNHA5,$SEXOTESTEMUNHA5,$PROFISSAOTESTEMUNHA5,$NACIONALIDADETESTEMUNHA5,$NATURALIDADETESTEMUNHA5,$DATANASCIMENTOTESTEMUNHA5,$ESTADOCIVILTESTEMUNHA5,$ENDERECOTESTEMUNHA5,$BAIRROTESTEMUNHA5,$CIDADETESTEMUNHA5,"","");

echo $IDTESTEMUNHA5."<br>";



echo "OBTENDOS DADOS DO TESTEMUNHA6: <br>";


$NOMETESTEMUNHA6 = $b->NOMETESTEMUNHA6;
$CPFTESTEMUNHA6 = $b->CPFTESTEMUNHA6;
$NACIONALIDADETESTEMUNHA6 = $b->NACIONALIDADETESTEMUNHA6;
$NATURALIDADETESTEMUNHA6 = $b->NATURALIDADETESTEMUNHA6;
$RGTESTEMUNHA6 = $b->RGTESTEMUNHA6;
$ORGAOEMISSORTESTEMUNHA6 = $b->ORGAOEMISSORTESTEMUNHA6;
$CIDADETESTEMUNHA6 = $b->CIDADETESTEMUNHA6;
$ENDERECOTESTEMUNHA6 = $b->ENDERECOTESTEMUNHA6;
$BAIRROTESTEMUNHA6 = $b->BAIRROTESTEMUNHA6;
$ESTADOCIVILTESTEMUNHA6 = $b->ESTADOCIVILTESTEMUNHA6;
$DATANASCIMENTOTESTEMUNHA6 = $b->DATANASCIMENTOTESTEMUNHA6;
$SEXOTESTEMUNHA6 = $b->SEXOTESTEMUNHA6;
$PROFISSAOTESTEMUNHA6 = $b->PROFISSAOTESTEMUNHA6;



$IDTESTEMUNHA6 = insertpessoa($NOMETESTEMUNHA6,'F',$CPFTESTEMUNHA6,$RGTESTEMUNHA6,$ORGAOEMISSORTESTEMUNHA6,$SEXOTESTEMUNHA6,$PROFISSAOTESTEMUNHA6,$NACIONALIDADETESTEMUNHA6,$NATURALIDADETESTEMUNHA6,$DATANASCIMENTOTESTEMUNHA6,$ESTADOCIVILTESTEMUNHA6,$ENDERECOTESTEMUNHA6,$BAIRROTESTEMUNHA6,$CIDADETESTEMUNHA6,"","");

echo $IDTESTEMUNHA6."<br>";



echo "----------------------------------------------------- <br>";



$jsondados = '
{

"IDPESSOANUBENTE1":"'.$IDNUBENTE1.'",
"IDPESSOAPAINUBENTE1":"'.$IDPAINUBENTE1.'",
"IDPESSOAMAENUBENTE1":"'.$IDMAENUBENTE1.'",
"IDPESSOANUBENTE2":"'.$IDNUBENTE2.'",
"IDPESSOAPAINUBENTE2":"'.$IDPAINUBENTE2.'",
"IDPESSOAMAENUBENTE2":"'.$IDMAENUBENTE2.'",
"IDPESSOATESTEMUNHA1":"'.$IDTESTEMUNHA1.'",
"IDPESSOATESTEMUNHA2":"'.$IDTESTEMUNHA2.'",
"IDPESSOAROGONUBENTE1":"'.$IDTESTEMUNHA3.'",
"IDPESSOAROGO2NUBENTE1":"'.$IDTESTEMUNHA4.'",
"IDPESSOAROGONUBENTE2":"'.$IDTESTEMUNHA5.'",
"IDPESSOAROGO2NUBENTE2":"'.$IDTESTEMUNHA6.'"


}';
*/


if ($b->SELO == '') {
UPDATE_CAMPO_ID("registro_casamento_novo", "status","ACV",$b->ID);
}

/*
if (empty($b->JSON_DADOS_ADD)) {
 UPDATE_CAMPO_ID("registro_casamento_novo", "JSON_DADOS_ADD", $jsondados, $b->ID);
}
else{
$jsonbd = str_replace("}", "", $b->JSON_DADOS_ADD);
$jsonbd = $jsonbd.$jsondados.'}';
UPDATE_CAMPO_ID("registro_casamento_novo", "JSON_DADOS_ADD", $jsonbd, $b->ID);
}

*/


} 


 ?>